export default {
  page_content_placeholder: 'Page content should be there',
  footer: 'Footer',
  header: 'Calculator App',
  history: 'History',
  access_denied: 'You have no access to open this page',
  return_home: 'Return Home',
  page_not_found: 'Requested page is not found',
  header_home_link: 'Home',
  header_settings_link: 'Settings',
  settings: 'Settings',
  clear_all_history: 'Clear All History',
  cleared: 'Cleared!',
  error: 'Error: ',
  light: 'Light',
  dark: 'Dark',
  undo: 'Undo',
}
