export default {
  page_content_placeholder: 'Содержимое страницы',
  footer: 'Подвал',
  header: 'Калькулятор',
  history: 'История',
  access_denied: 'Для доступа к этой странице необходимо авторизоваться',
  return_home: 'Вернуться на главную страницу',
  page_not_found: 'Страница не найдена',
  header_home_link: 'Главная',
  header_settings_link: 'Настройки',
  settings: 'Настройки',
  clear_all_history: 'Очистить историю',
  cleared: 'Очищено!',
  error: 'Ошибка: ',
  light: 'Светлая',
  dark: 'Темная',
  undo: 'Отменить',
}
