export const light = {
  unit: {
    half: '4px',
    single: '8px',
    double: '16px',
    quadriple: '32px',
    eight: '64px',
  },
  colors: {
    background: '#ffffff',
    backgroundDark: '#f9f9f9',
    primary: '#fe2419',
    primaryDark: '#434343',
    secondary: '#26499d',
    secondaryLight: 'rgba(38, 73, 157, 0.73)',
    font: '#222222',
    gray: '#cccccc',
    darkGray: '#e4e4e4',
    fontDarkGray: '#e4e4e4',
    buttonBackground: '#f9f9f9',
  },
  fontSizes: {
    werySmall: '12px',
    small: '14px',
    normal: '16px',
    big: '20px',
    weryBig: '24px',
    extraBig: '36px',
  },
  letterSpacing: {
    normal: 'normal',
    caps: '0.25em',
  },
  fontWeights: {
    light: 300,
    normal: 400,
    bold: 700,
  },
  fontFamily: ['Lato, "Helvetica Neue", Arial'],
}

export const dark = {
  unit: {
    half: '4px',
    single: '8px',
    double: '16px',
    quadriple: '32px',
    eight: '64px',
  },
  colors: {
    background: '#a0a0a0',
    backgroundDark: '#f9f9f9',
    primary: '#fe2419',
    primaryDark: '#434343',
    secondary: '#26499d',
    secondaryLight: 'rgba(38, 73, 157, 0.73)',
    font: '#fff',
    gray: '#cccccc',
    darkGray: '#5c5c5c',
    fontDarkGray: '#e4e4e4',
    buttonBackground: '#434343',
  },
  fontSizes: {
    werySmall: '12px',
    small: '14px',
    normal: '16px',
    big: '20px',
    weryBig: '24px',
    extraBig: '36px',
  },
  letterSpacing: {
    normal: 'normal',
    caps: '0.25em',
  },
  fontWeights: {
    light: 300,
    normal: 400,
    bold: 700,
  },
  fontFamily: ['Lato, "Helvetica Neue", Arial'],
}
